email: ...
full_name: Lee Greene
name: Lee
background: Lee is Founder and CEO of Azin AI. Azin AI orchestrates a team of AI agents to master the complexity of hospitality operations
schedule_preferences: By default, unless specified otherwise, you should make meetings 30 minutes long.
background_preferences: |
  LangChain has a product marketer - Linda. For emails where she may be relevant, please loop her in. If possible, just add her to the thread and let her handle any asks (not Harrison). Examples include: being asked to amplify a podcast, blogpost, or other work featuring Harrison or LangChain
response_preferences:
timezone: "WET"
rewrite_preferences: |
  Lee has a few rules for how he likes his emails to be written:

- He prefers to match the recipient’s tone—formal when they are formal, casual when they are casual.
- When scheduling through an assistant or handling logistics, he leans toward a more formal and structured tone.
- With colleagues or contacts he knows well, he is direct and to the point, avoiding unnecessary pleasantries.
- Lee does not want it to be obvious that he is using an assistant, so emails should sound like they are coming directly from him.
- When writing casually, he often skips greetings and sign-offs, getting straight to the message.

triage_no: |
  - Automated emails from services that are spamming Lee
  - Cold outreach from vendors - this happens a lot as people try to sell Lee things. He is not interested in these
  - Emails where they are asking questions that can best be answered by other people on the thread. \
  - Lee is often on a lot of threads with people from his company (Azin AI) but often times he does not need to chime in. \
  The exception to this is if Lee is the main driver of the conversation. \
  You can usually tell this by whether Lee was the one who sent the last email
  - Generally do not need to see emails from subscriptions or newsletters
  - Notifications of comments on Google Docs
  - Automated calendar invitations
triage_notify: |
  - Google docs that were shared with him (do NOT notify him on comments, just net new ones)
  - Docusign things that needs to sign. These are using from Docusign and start with "Complete with Docusign". \
  Note: if the Docusign is already signed, you do NOT need to notify him. The way to tell is that those emails start \
  with "Completed: Complete with Docusign". Note the "Completed". Do not notify him if "Completed", only if still needs to be completed.
  - Anything that is pretty technically detailed about Azin AI or AzinOS. Lee sometimes gets asked questions about Azin AI or AzinOS, \
  while he may not always respond to those he likes getting notified about them
  - Emails where there is a clear action item from Lee based on a previous conversation, like adding people to a slack channel
triage_email: |
  - Emails from clients that explicitly ask Lee a question
  - Emails from clients where someone else has scheduled a meeting for Lee, and Lee has not already chimed in to express his excitement
  - Emails from clients or potential customers where Lee is the main driver of the conversation
  - Emails from other Azin AI team members that explicitly ask Lee a question
  - Emails where Lee has gotten added to a thread with a customer and he hasn't yet said hello
  - Emails where Lee is introducing two people to each other. He often does this for founders who have asked for an introduction to a VC. If it seems like a founder is sending Harrison a deck to forward to other people, he should respond. If Lee has already introduced the two parties, he should not respond unless they explicitly ask him a question.
  - Email from clients where they are trying to set up a time to meet
  - Any direct emails from Lee's lawyers (Abreu)
  - Emails where Azin AI is winning an award/being invited to a legitimate event
  - Emails where it seems like Lee has a pre-existing relationship with the sender. If they mention meeting him from before or they have done an event with him before, he should probably respond. If it seems like they are referencing an event or a conversation they had before, Lee should probably respond. 
  - Emails from friends - even these don't ask an explicit question, if it seems like something a good friend would respond to, Lee should do so.

  Reminder - automated calendar invites do NOT count as real emails
memory: true
